### ISSUE TITLE
Add more level gameplay features

### ISSUE THREAD

**Issue by mindoodoo** [Epitech-R-Type/R-Type#131]
Here's a couple ideas for the level handling and what not:

- Implement wave based system
    - **wave =**  multiple enemies + one boss
    - **NO** enemies during the boss phase
    - After a given wave, little **break** in enemy spawning, then second wave starts
- Implement **end of game** after certain number of waves
    - This number of waves **should** be part of the level specification

I don't know if this is already done, but if not, the ability to determine **possible enemies** and **spawn chance** for each wave would be cool.

**Comment by klemmse** [comment]
The music is missing in the level file. maybe have an i for normal music and boss music
