### ISSUE TITLE
Add client input

### ISSUE THREAD

**Issue by klemmse** [Epitech-R-Type/R-Type#46]
This issue is about the user input and what to do with it. The current idea was to check the input related to a timer. But I don't know if we want to handle the input on the client side aswell or not. I am also not sure how to implement it with the other systems, maybe someone has an idea.

**Comment by mindoodoo** [comment]
@klemmse @theCaptain136 What is this issue about, could you provide a little description ?

**Comment by klemmse** [comment]
@mindoodoo @nLatt the description is updated and I would like to have a comment from you guys.

**Comment by nLatt** [comment]
The user movement system will be 100 % Client side, imagine your standard input gathering system, and that is basically it, update the user entities position component with whatrever value you decide on at first, later on we will also send a message notifying the server of this movement
